POST http://127.0.0.1:8080/generate HTTP/1.1
content-type: application/json

{
    "location": {
        "city_name":"Dallas",
        "country_name":"United States"
    },
    "industry": "Fishing Boat Charter",
    "secret":"magic"
}